baseURL = "http://example.org/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "OSDC"
title = "Mercurius"
paginate = 10
enableRobotsTXT = true
theme = "drizzle"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta description in head part
	description = "OSDC Newsletter"

	# Add pagetitle to homepage <title> tag
	pagetitle = "Home"

	# Add a subtitle to your website
	subtitle = "An OSDC Newsletter"

	# Activate to show authors on pages if available
	#listAuthor = true

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	# avatar = "/img/vitae.jpg"

	# Optional favicons for website
	#favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

# Social Menu
[[params.social]]
name = "Twitter"
icon = "fab fa-twitter"
url = "https://twitter.com/osdcjiit"

[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/osdc/Mercurius"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"